name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'sahkosampo-nodejs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./sahkosampo-nodejs
          push: true
          tags: ghcr.io/Paisto-Oy/homeassistant-sahkosampo-addon/sahkosampo-nodejs:latest
          platforms: linux/amd64,linux/armv7,linux/aarch64